"""F-34: add tax engine fields to tenant, product and sale

Revision ID: 4bc9046d91ad
Revises: 3e509476aa86
Create Date: 2026-06-15 21:24:08.301818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc9046d91ad'
down_revision: Union[str, None] = '3e509476aa86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_tax_exempt', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sales', sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('sales', sa.Column('retention_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
    op.add_column('tenants', sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=4), server_default='0.19', nullable=False))
    op.add_column('tenants', sa.Column('default_retention_rate', sa.Numeric(precision=5, scale=4), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'default_retention_rate')
    op.drop_column('tenants', 'default_vat_rate')
    op.drop_column('sales', 'retention_amount')
    op.drop_column('sales', 'tax_amount')
    op.drop_column('sales', 'subtotal')
    op.drop_column('products', 'is_tax_exempt')
    # ### end Alembic commands ###
