"""F-35: add branches, branch_product_stock, sale_branch_id

Revision ID: 605b14acfe73
Revises: 4bc9046d91ad
Create Date: 2026-06-15 22:12:05.947465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605b14acfe73'
down_revision: Union[str, None] = '4bc9046d91ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_tenant_id'), 'branches', ['tenant_id'], unique=False)
    op.create_table('branch_product_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_id', name='uq_branch_product')
    )
    op.create_index(op.f('ix_branch_product_stock_branch_id'), 'branch_product_stock', ['branch_id'], unique=False)
    op.create_index(op.f('ix_branch_product_stock_product_id'), 'branch_product_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_branch_product_stock_tenant_id'), 'branch_product_stock', ['tenant_id'], unique=False)
    op.add_column('sales', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sales_branch_id'), 'sales', ['branch_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_branch_id'), table_name='sales')
    op.drop_column('sales', 'branch_id')
    op.drop_index(op.f('ix_branch_product_stock_tenant_id'), table_name='branch_product_stock')
    op.drop_index(op.f('ix_branch_product_stock_product_id'), table_name='branch_product_stock')
    op.drop_index(op.f('ix_branch_product_stock_branch_id'), table_name='branch_product_stock')
    op.drop_table('branch_product_stock')
    op.drop_index(op.f('ix_branches_tenant_id'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
