"""fase8_admin_audit

Revision ID: e82abcff53cb
Revises: 885ca5a639c1
Create Date: 2026-04-21 02:42:52.840342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82abcff53cb'
down_revision: Union[str, None] = '885ca5a639c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('old_plan', sa.Enum('FREE', 'BASIC', 'PRO', name='planenum'), nullable=False),
    sa.Column('new_plan', sa.Enum('FREE', 'BASIC', 'PRO', name='planenum'), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_audit_log_tenant_id'), 'plan_audit_log', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_audit_log_tenant_id'), table_name='plan_audit_log')
    op.drop_table('plan_audit_log')
    # ### end Alembic commands ###
