"""F-32: add purchase_orders and purchase_order_items tables

Revision ID: fbaca70298f9
Revises: e82abcff53cb
Create Date: 2026-06-15 04:27:47.321615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaca70298f9'
down_revision: Union[str, None] = 'e82abcff53cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
